### ISSUE TITLE
RGB working?

### ISSUE THREAD

**Issue by dennischen0** [foureight84/sofle-keyboard-pimoroni#1]
Is Rgb working with the lates develop branch? I'm trying to get it to light up but am not getting any success. Also, it seems like the Pimoroni trackball is pretty difficult to use as a mouse pointer. Is this expected?

Thanks!

**Comment by foureight84** [comment]
The trackball movement is expected since the resolution is fairly low for use against a high-resolution monitor. There's an upcoming PR that aims to improve this (https://github.com/qmk/qmk_firmware/pull/16371). I generally use it while coding where it's not required to move the mouse across the screen. 

As for the RGB, I am not using that feature on my keyboard and I do not know if there are outstanding issues within the develop branch. You may want to inquire in the QMK discord.
